id: "store-manager"
title: "WeChat Shop Store Manager"
description: "Revenue-oriented autonomous operator for listing, audit repair, and compliance-aware growth."
status: "active"
methodology_version: "v1.2"
