#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export TMPDIR="${TMPDIR:-$ROOT_DIR/.tmp}"
mkdir -p "$TMPDIR"
cd "$ROOT_DIR"

python3 scripts/validate_non_owner_machine_law_reinforcement_admission.py --json-only >/dev/null

python3 -c 'import sys, tempfile; from pathlib import Path; root = Path(".").resolve(); sys.path.insert(0, str(root)); import scripts.non_owner_machine_law_reinforcement_admission_contract_common as c; payload = c.baseline_payload(); td = tempfile.TemporaryDirectory(); tmp = Path(td.name); paths = {"governance": tmp / "governance.md", "review": tmp / "review.md", "workbook": tmp / "workbook.md", "issue_register": tmp / "issue-register.md"}; c.write_artifacts(); paths["governance"].write_text((root / "docs/governance/identity-non-owner-machine-law-reinforcement-admission-governance-v1.6.x.md").read_text(encoding="utf-8"), encoding="utf-8"); paths["review"].write_text((root / "docs/review/protocol-remediation-audit-ledger-v1.6.x-non-owner-machine-law-reinforcement-admission.md").read_text(encoding="utf-8"), encoding="utf-8"); paths["workbook"].write_text((root / "docs/workbook/protocol-deep-audit-workbook-v1.6.md").read_text(encoding="utf-8"), encoding="utf-8"); paths["issue_register"].write_text((root / "docs/workbook/protocol-issue-register-v1.6.md").read_text(encoding="utf-8"), encoding="utf-8"); gov = c.read_text(paths["governance"]); rev = c.read_text(paths["review"]); wb = c.read_text(paths["workbook"]); ir = c.read_text(paths["issue_register"]); reasons = []; reasons.extend(c.validate_doc_tokens("governance", gov)); reasons.extend(c.validate_doc_tokens("review", rev)); reasons.extend(c.validate_workbook_text(wb)); reasons.extend(c.validate_issue_register_text(ir)); gp = c.extract_payload_from_text(gov, "governance"); rp = c.extract_payload_from_text(rev, "review"); reasons.extend(c.validate_reinforcement_payload(gp)); reasons.extend(c.validate_reinforcement_payload(rp)); assert not reasons, reasons; assert gp == rp, (gp, rp); assert "ISSUE-043" in wb and "ISSUE-043" in ir; assert "ISSUE-044" in wb and "ISSUE-045" in wb; assert "ISSUE-044" in ir and "ISSUE-045" in ir; td.cleanup()'

python3 -c 'import sys; from pathlib import Path; sys.path.insert(0, str(Path(".").resolve())); import scripts.non_owner_machine_law_reinforcement_admission_contract_common as c; payload = c.baseline_payload(); payload["reinforcement_entry_surface"] = "consumer"; payload["accepted_root_law_ref"] = "ISSUE-045"; payload["reinforcement_scope_status"] = "bounded"; reasons = c.validate_reinforcement_payload(payload); assert not reasons, reasons'

python3 -c 'import sys; from pathlib import Path; sys.path.insert(0, str(Path(".").resolve())); import scripts.non_owner_machine_law_reinforcement_admission_contract_common as c; payload = c.baseline_payload(); payload["reinforcement_entry_surface"] = "middle"; payload["root_semantic_redefinition_status"] = "redefined"; reasons = c.validate_reinforcement_payload(payload); assert any("root_semantic_redefinition_status" in reason or "root_semantic" in reason or "redefinition" in reason for reason in reasons), reasons'

python3 -c 'import sys; from pathlib import Path; sys.path.insert(0, str(Path(".").resolve())); import scripts.non_owner_machine_law_reinforcement_admission_contract_common as c; payload = c.baseline_payload(); payload["canonical_owner_truth_preservation_status"] = "replaced"; reasons = c.validate_reinforcement_payload(payload); assert any("canonical_owner_truth_preservation_status" in reason or "owner_truth" in reason for reason in reasons), reasons'

python3 -c 'import sys; from pathlib import Path; sys.path.insert(0, str(Path(".").resolve())); import scripts.non_owner_machine_law_reinforcement_admission_contract_common as c; payload = c.baseline_payload(); payload["whole_lane_completion_target"] = "reopen_whole_lane"; payload["whole_lane_completion_status"] = "reopened"; reasons = c.validate_reinforcement_payload(payload); assert any("whole_lane_completion_target" in reason or "whole_lane_completion_status" in reason or "whole_lane" in reason for reason in reasons), reasons'

python3 -c 'import sys, tempfile; from pathlib import Path; root = Path(".").resolve(); sys.path.insert(0, str(root)); import scripts.non_owner_machine_law_reinforcement_admission_contract_common as c; payload = c.baseline_payload(); td = tempfile.TemporaryDirectory(); tmp = Path(td.name); paths = {"governance": tmp / "governance.md", "review": tmp / "review.md", "workbook": tmp / "workbook.md", "issue_register": tmp / "issue-register.md"}; c.write_artifacts(); paths["governance"].write_text((root / "docs/governance/identity-non-owner-machine-law-reinforcement-admission-governance-v1.6.x.md").read_text(encoding="utf-8"), encoding="utf-8"); paths["review"].write_text((root / "docs/review/protocol-remediation-audit-ledger-v1.6.x-non-owner-machine-law-reinforcement-admission.md").read_text(encoding="utf-8"), encoding="utf-8"); paths["workbook"].write_text((root / "docs/workbook/protocol-deep-audit-workbook-v1.6.md").read_text(encoding="utf-8"), encoding="utf-8"); paths["issue_register"].write_text((root / "docs/workbook/protocol-issue-register-v1.6.md").read_text(encoding="utf-8"), encoding="utf-8"); review_text = c.read_text(paths["review"]).replace("\"accepted_root_law_ref\": \"ISSUE-045 accepted root law\"", "\"accepted_root_law_ref\": \"ISSUE-999 mutated root law\"", 1); paths["review"].write_text(review_text, encoding="utf-8"); gp = c.extract_payload_from_text(c.read_text(paths["governance"]), "governance"); rp = c.extract_payload_from_text(c.read_text(paths["review"]), "review"); assert gp != rp, (gp, rp); td.cleanup()'

python3 -c 'import sys, tempfile; from pathlib import Path; root = Path(".").resolve(); sys.path.insert(0, str(root)); import scripts.non_owner_machine_law_reinforcement_admission_contract_common as c; payload = c.baseline_payload(); td = tempfile.TemporaryDirectory(); tmp = Path(td.name); paths = {"governance": tmp / "governance.md", "review": tmp / "review.md", "workbook": tmp / "workbook.md", "issue_register": tmp / "issue-register.md"}; paths["workbook"].write_text((root / "docs/workbook/protocol-deep-audit-workbook-v1.6.md").read_text(encoding="utf-8"), encoding="utf-8"); paths["issue_register"].write_text((root / "docs/workbook/protocol-issue-register-v1.6.md").read_text(encoding="utf-8"), encoding="utf-8"); c.write_artifacts(); workbook_text = c.read_text(paths["workbook"]).replace("ISSUE-045", "ISSUE-043", 1); issue_register_text = c.read_text(paths["issue_register"]).replace("ISSUE-045", "ISSUE-043", 1); assert "ISSUE-045" not in workbook_text or "ISSUE-045" not in issue_register_text; td.cleanup()'

echo PASS
