#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml


def _append_jsonl(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a', encoding='utf-8') as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def _append_task_history(path: Path, line: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a', encoding='utf-8') as f:
        f.write(f"\n- {line}\n")


def _load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding='utf-8')) or {}
    if not isinstance(data, dict):
        raise ValueError(f"yaml root must be object: {path}")
    return data


def _resolve_pack(catalog_path: Path, identity_id: str) -> Path:
    catalog = _load_yaml(catalog_path)
    identities = catalog.get('identities') or []
    target = next((x for x in identities if str((x or {}).get('id', '')).strip() == identity_id), None)
    if not isinstance(target, dict):
        raise FileNotFoundError(f"identity id not found in catalog: {identity_id}")
    pack_path = str(target.get('pack_path', '')).strip()
    if not pack_path:
        raise ValueError(f"catalog entry missing pack_path for identity: {identity_id}")
    p = Path(pack_path).expanduser().resolve()
    if not p.exists():
        raise FileNotFoundError(f"pack_path does not exist: {p}")
    return p


def _assert_scoped_writeback(identity_id: str, pack: Path, rulebook_path: Path, history_path: Path, report_identity_id: str) -> None:
    if report_identity_id and report_identity_id != identity_id:
        raise ValueError(
            f"report identity mismatch: report={report_identity_id} requested={identity_id}"
        )
    expected_rulebook = (pack / 'RULEBOOK.jsonl').resolve()
    expected_history = (pack / 'TASK_HISTORY.md').resolve()
    if rulebook_path.resolve() != expected_rulebook:
        raise ValueError(
            f"rulebook path not identity-scoped: got={rulebook_path.resolve()} expected={expected_rulebook}"
        )
    if history_path.resolve() != expected_history:
        raise ValueError(
            f"task history path not identity-scoped: got={history_path.resolve()} expected={expected_history}"
        )


def main() -> int:
    ap = argparse.ArgumentParser(description='Apply deferred identity writeback report generated by execute_identity_upgrade.py')
    ap.add_argument('--report', required=True, help='path to *-writeback-deferred.json')
    ap.add_argument('--identity-id', required=True, help='identity id expected for this deferred report')
    ap.add_argument('--catalog', required=True, help='catalog used to resolve pack path for identity-scoped writeback')
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()

    report_path = Path(args.report)
    data = json.loads(report_path.read_text(encoding='utf-8'))
    intended = data.get('intended_writeback') or {}

    rulebook_path = Path(str(intended.get('rulebook_path', '')).strip())
    history_path = Path(str(intended.get('task_history_path', '')).strip())
    rulebook_row = intended.get('rulebook_row') or {}
    history_line = str(intended.get('task_history_line', '')).strip()

    if not rulebook_path or not history_path or not history_line:
        raise ValueError('deferred report missing required intended_writeback fields')

    report_identity_id = str(data.get('identity_id', '')).strip()
    pack = _resolve_pack(Path(args.catalog).expanduser().resolve(), args.identity_id)
    _assert_scoped_writeback(
        args.identity_id,
        pack,
        rulebook_path,
        history_path,
        report_identity_id,
    )

    print(f"identity_id={args.identity_id}")
    print(f"run_id={data.get('run_id','')}")
    print(f"rulebook_path={rulebook_path.resolve()}")
    print(f"task_history_path={history_path.resolve()}")

    if args.dry_run:
        print('dry_run=true (no file changes applied)')
        return 0

    _append_jsonl(rulebook_path.resolve(), rulebook_row)
    _append_task_history(history_path.resolve(), history_line)

    applied = {
        'source_deferred_report': str(report_path),
        'applied': True,
        'identity_id': args.identity_id,
        'catalog_path': str(Path(args.catalog).expanduser().resolve()),
        'pack_path': str(pack),
        'rulebook_path': str(rulebook_path.resolve()),
        'task_history_path': str(history_path.resolve()),
    }
    applied_path = report_path.with_name(report_path.stem + '-applied.json')
    applied_path.write_text(json.dumps(applied, ensure_ascii=False, indent=2) + "\n", encoding='utf-8')
    print(f"applied_report={applied_path}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
