#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def _append_jsonl(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a', encoding='utf-8') as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def _append_task_history(path: Path, line: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a', encoding='utf-8') as f:
        f.write(f"\n- {line}\n")


def main() -> int:
    ap = argparse.ArgumentParser(description='Apply deferred identity writeback report generated by execute_identity_upgrade.py')
    ap.add_argument('--report', required=True, help='path to *-writeback-deferred.json')
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()

    report_path = Path(args.report)
    data = json.loads(report_path.read_text(encoding='utf-8'))
    intended = data.get('intended_writeback') or {}

    rulebook_path = Path(str(intended.get('rulebook_path', '')).strip())
    history_path = Path(str(intended.get('task_history_path', '')).strip())
    rulebook_row = intended.get('rulebook_row') or {}
    history_line = str(intended.get('task_history_line', '')).strip()

    if not rulebook_path or not history_path or not history_line:
        raise ValueError('deferred report missing required intended_writeback fields')

    print(f"identity_id={data.get('identity_id','')}")
    print(f"run_id={data.get('run_id','')}")
    print(f"rulebook_path={rulebook_path}")
    print(f"task_history_path={history_path}")

    if args.dry_run:
        print('dry_run=true (no file changes applied)')
        return 0

    _append_jsonl(rulebook_path, rulebook_row)
    _append_task_history(history_path, history_line)

    applied = {
        'source_deferred_report': str(report_path),
        'applied': True,
        'rulebook_path': str(rulebook_path),
        'task_history_path': str(history_path),
    }
    applied_path = report_path.with_name(report_path.stem + '-applied.json')
    applied_path.write_text(json.dumps(applied, ensure_ascii=False, indent=2) + "\n", encoding='utf-8')
    print(f"applied_report={applied_path}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
