#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import shlex
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from workspace_runtime_closure_command_common import (
    build_workspace_runtime_closure_checker_command,
)

STATUS_PASS_REQUIRED = "PASS_REQUIRED"
STATUS_FAIL_REQUIRED = "FAIL_REQUIRED"

LAUNCHER_CONVERGENCE_STREAM_VERSION = "v1.6.14"
LAUNCHER_CONVERGENCE_EVIDENCE_TOPIC = "identity_codex_launcher_workspace_convergence"
LAUNCHER_CONVERGENCE_MANIFEST_PREFIX = "EVIDENCE_MANIFEST"
LAUNCHER_CONVERGENCE_ENTRY_ID = "scripts/run_identity_codex_launcher_workspace_convergence.py"
LAUNCHER_CONVERGENCE_MANIFEST_NOTES: tuple[str, ...] = (
    "Launcher convergence evidence truth-sync keeps receipt self-reference and manifest archival aligned.",
    "Generated by refresh_identity_codex_launcher_evidence_truth_sync.py or by the convergence entry itself.",
)


def normalize_run_token(run_token: str) -> str:
    safe_token = "".join(
        ch if ch.isalnum() or ch in {"-", "_", "."} else "-" for ch in str(run_token or "").strip()
    )
    return safe_token or "run"


def artifact_path(root: Path, stem: str, run_token: str) -> Path:
    return (root / f"{stem}.{normalize_run_token(run_token)}_summary.json").resolve()


def manifest_path(root: Path, run_token: str) -> Path:
    return (root / f"{LAUNCHER_CONVERGENCE_MANIFEST_PREFIX}.{normalize_run_token(run_token)}.json").resolve()


def launcher_convergence_manifest_notes() -> list[str]:
    return list(LAUNCHER_CONVERGENCE_MANIFEST_NOTES)


def launcher_convergence_entry_command(
    *,
    repo_root: Path,
    catalog_path: Path,
    mode: str,
    artifact_root: Path,
    run_token: str,
    receipt_path: Path,
    codex_home: Path | None = None,
) -> list[str]:
    cmd = [
        "python3",
        str((repo_root / LAUNCHER_CONVERGENCE_ENTRY_ID).resolve()),
        "--catalog",
        str(catalog_path.resolve()),
        "--mode",
        str(mode or "").strip(),
    ]
    if codex_home is not None:
        cmd.extend(["--codex-home", str(codex_home.resolve())])
    cmd.extend(
        [
            "--artifact-root",
            str(artifact_root.resolve()),
            "--run-token",
            str(run_token or "").strip(),
            "--out",
            str(receipt_path.resolve()),
            "--json-only",
        ]
    )
    return cmd


def launcher_convergence_closure_checker_command(*, repo_root: Path, catalog_path: Path) -> list[str]:
    return build_workspace_runtime_closure_checker_command(
        checker_id="scripts/check_identity_codex_launcher_migration_closure.py",
        repo_root=repo_root.resolve(),
        repo_catalog_path="identity/catalog/identities.yaml",
        catalog_path=catalog_path.resolve(),
        json_only=True,
    )


def load_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"expected JSON object at {path}")
    return data


def resolve_manifest_member(manifest_path: Path, value: str) -> Path:
    raw = Path(str(value).strip())
    if raw.is_absolute():
        return raw.resolve()
    return (manifest_path.parent / raw).resolve()


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(canonical_json_bytes(payload))


def canonical_json_bytes(payload: dict[str, Any]) -> bytes:
    return (json.dumps(payload, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def path_ref(path: Path, workspace_root: Path) -> str:
    resolved = path.resolve()
    try:
        return resolved.relative_to(workspace_root.resolve()).as_posix()
    except ValueError:
        return str(resolved)


def file_timestamp(path: Path) -> str:
    return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc).isoformat().replace("+00:00", "Z")


def command_string(command: str | Iterable[str]) -> str:
    if isinstance(command, str):
        return command.strip()
    return shlex.join([str(part) for part in command if str(part).strip()])


def inspect_launcher_convergence_manifest(
    *,
    manifest_path: Path,
    expected_kinds: Iterable[str] | None = None,
    require_summary_ref: bool = False,
) -> dict[str, Any]:
    manifest_path = manifest_path.resolve()
    manifest = load_json(manifest_path)
    evidence_records = manifest.get("evidence_records")
    expected_kind_set = {
        str(kind).strip()
        for kind in (expected_kinds or [])
        if str(kind).strip()
    }
    errors: list[str] = []
    validated_kinds: list[str] = []
    missing_mirror_paths: list[str] = []
    digest_mismatches: list[str] = []
    record_count = 0

    summary_ref = str(manifest.get("summary_ref", "")).strip()
    if require_summary_ref and not summary_ref:
        errors.append("manifest_summary_ref_missing")

    if not isinstance(evidence_records, list) or not evidence_records:
        errors.append("manifest_evidence_records_missing")
        evidence_records = []

    for row in evidence_records:
        if not isinstance(row, dict):
            errors.append("manifest_record_invalid")
            continue
        record_count += 1
        kind = str(row.get("kind", "")).strip()
        if kind:
            validated_kinds.append(kind)
        mirror_value = str(row.get("mirror_path", "")).strip()
        if not mirror_value:
            errors.append("manifest_mirror_path_missing")
            continue
        mirror_path = resolve_manifest_member(manifest_path, mirror_value)
        if not mirror_path.exists():
            missing_mirror_paths.append(str(mirror_path))
            continue
        expected_digest = str(row.get("sha256", "")).strip()
        if not expected_digest:
            errors.append("manifest_sha256_missing")
            continue
        actual_digest = sha256_file(mirror_path)
        if actual_digest != expected_digest:
            digest_mismatches.append(str(mirror_path))

    validated_kind_set = {kind for kind in validated_kinds if kind}
    if expected_kind_set and validated_kind_set != expected_kind_set:
        errors.append("manifest_expected_kind_set_mismatch")

    if missing_mirror_paths:
        errors.append("manifest_mirror_path_unavailable")
    if digest_mismatches:
        errors.append("manifest_sha256_mismatch")

    return {
        "status": STATUS_PASS_REQUIRED if not errors else STATUS_FAIL_REQUIRED,
        "manifest_path": str(manifest_path),
        "summary_ref": summary_ref,
        "record_count": record_count,
        "validated_kinds": sorted(validated_kind_set),
        "expected_kinds": sorted(expected_kind_set),
        "missing_kinds": sorted(expected_kind_set - validated_kind_set),
        "unexpected_kinds": sorted(validated_kind_set - expected_kind_set),
        "missing_mirror_paths": missing_mirror_paths,
        "digest_mismatches": digest_mismatches,
        "errors": errors,
        "manifest": manifest,
    }


def inspect_launcher_convergence_payload_bundle(
    *,
    payload: dict[str, Any],
    required_ref_fields: Iterable[str] | None = None,
    expected_kinds: Iterable[str] | None = None,
    require_summary_ref: bool = False,
) -> dict[str, Any]:
    required_fields = [
        str(field).strip()
        for field in (required_ref_fields or [])
        if str(field).strip()
    ]
    resolved_ref_paths: dict[str, str] = {}
    missing_ref_fields: list[str] = []
    missing_ref_paths: list[str] = []
    errors: list[str] = []

    for field in required_fields:
        raw = str(payload.get(field, "")).strip()
        if not raw:
            missing_ref_fields.append(field)
            continue
        resolved = Path(raw).expanduser().resolve()
        resolved_ref_paths[field] = str(resolved)
        if not resolved.exists():
            missing_ref_paths.append(field)

    manifest_token = str(payload.get("manifest_ref", "")).strip()
    manifest_path: Path | None = None
    manifest_inspection: dict[str, Any] = {}
    if manifest_token:
        manifest_path = Path(manifest_token).expanduser().resolve()
        if not manifest_path.exists():
            missing_ref_paths.append("manifest_ref")
        else:
            manifest_inspection = inspect_launcher_convergence_manifest(
                manifest_path=manifest_path,
                expected_kinds=expected_kinds,
                require_summary_ref=require_summary_ref,
            )
            if str(manifest_inspection.get("status", "")).strip() != STATUS_PASS_REQUIRED:
                errors.extend(
                    [
                        str(item).strip()
                        for item in (manifest_inspection.get("errors") or [])
                        if str(item).strip()
                    ]
                )
    elif expected_kinds or require_summary_ref:
        missing_ref_fields.append("manifest_ref")

    if missing_ref_fields:
        errors.append("bundle_required_ref_missing")
    if missing_ref_paths:
        errors.append("bundle_required_ref_path_missing")

    return {
        "status": STATUS_PASS_REQUIRED if not errors else STATUS_FAIL_REQUIRED,
        "required_ref_fields": required_fields,
        "resolved_ref_paths": resolved_ref_paths,
        "missing_ref_fields": missing_ref_fields,
        "missing_ref_paths": missing_ref_paths,
        "errors": errors,
        "manifest_status": str(manifest_inspection.get("status", "")).strip() if manifest_inspection else "",
        "manifest_inspection": manifest_inspection,
    }


def inspect_launcher_convergence_receipt_bundle(
    *,
    receipt_path: Path,
    expected_kinds: Iterable[str] | None = None,
    require_summary_ref: bool = False,
    require_self_evidence_ref_match: bool = False,
) -> dict[str, Any]:
    receipt_path = receipt_path.resolve()
    payload = load_json(receipt_path)
    inspection = inspect_launcher_convergence_payload_bundle(
        payload=payload,
        required_ref_fields=("evidence_ref", "manifest_ref"),
        expected_kinds=expected_kinds,
        require_summary_ref=require_summary_ref,
    )
    errors = [str(item).strip() for item in (inspection.get("errors") or []) if str(item).strip()]
    evidence_ref = str(payload.get("evidence_ref", "")).strip()
    if require_self_evidence_ref_match and evidence_ref and Path(evidence_ref).expanduser().resolve() != receipt_path:
        errors.append("receipt_evidence_ref_mismatch")
    inspection["receipt_path"] = str(receipt_path)
    inspection["receipt_evidence_ref"] = evidence_ref
    inspection["receipt_payload"] = payload
    inspection["errors"] = errors
    inspection["status"] = STATUS_PASS_REQUIRED if not errors else STATUS_FAIL_REQUIRED
    return inspection


def build_manifest_record(
    *,
    kind: str,
    path: Path,
    workspace_root: Path,
    command: str | Iterable[str],
    rc: int,
    timestamp: str = "",
    tmp_path: str = "",
    payload_override: dict[str, Any] | None = None,
) -> dict[str, Any]:
    sha256 = (
        hashlib.sha256(canonical_json_bytes(payload_override)).hexdigest()
        if payload_override is not None
        else sha256_file(path)
    )
    record: dict[str, Any] = {
        "kind": str(kind or "").strip(),
        "mirror_path": path_ref(path, workspace_root),
        "sha256": sha256,
        "command": command_string(command),
        "rc": int(rc),
        "timestamp": str(timestamp or file_timestamp(path)).strip(),
    }
    tmp_token = str(tmp_path or "").strip()
    if tmp_token:
        record["tmp_path"] = tmp_token
    return record


def build_launcher_convergence_manifest(
    *,
    workspace_root: Path,
    artifact_root: Path,
    receipt_path: Path,
    run_token: str,
    generated_at: str,
    mode: str,
    catalog_path: Path,
    entry_id: str,
    receipt_family: str,
    evidence_records: list[dict[str, Any]],
    notes: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "stream_version": LAUNCHER_CONVERGENCE_STREAM_VERSION,
        "topic": LAUNCHER_CONVERGENCE_EVIDENCE_TOPIC,
        "entry_id": str(entry_id or "").strip(),
        "receipt_family": str(receipt_family or "").strip(),
        "generated_at": str(generated_at or "").strip(),
        "workspace_root": str(workspace_root.resolve()),
        "artifact_root": str(artifact_root.resolve()),
        "evidence_root": path_ref(artifact_root, workspace_root),
        "summary_ref": path_ref(receipt_path, workspace_root),
        "run_token": normalize_run_token(run_token),
        "mode": str(mode or "").strip(),
        "catalog_path": str(catalog_path.resolve()),
        "notes": list(notes or []),
        "evidence_records": evidence_records,
    }


def materialize_launcher_convergence_bundle(
    *,
    workspace_root: Path,
    artifact_root: Path,
    receipt_path: Path,
    run_token: str,
    generated_at: str,
    mode: str,
    catalog_path: Path,
    entry_id: str,
    receipt_family: str,
    receipt_payload: dict[str, Any],
    evidence_record_inputs: list[dict[str, Any]],
    notes: list[str] | None = None,
    manifest_out: Path | None = None,
) -> tuple[dict[str, Any], Path, dict[str, Any]]:
    receipt_payload, manifest_out, manifest_payload = prepare_launcher_convergence_bundle(
        workspace_root=workspace_root,
        artifact_root=artifact_root,
        receipt_path=receipt_path,
        run_token=run_token,
        generated_at=generated_at,
        mode=mode,
        catalog_path=catalog_path,
        entry_id=entry_id,
        receipt_family=receipt_family,
        receipt_payload=receipt_payload,
        evidence_record_inputs=evidence_record_inputs,
        notes=notes,
        manifest_out=manifest_out,
    )
    write_json(receipt_path, receipt_payload)
    write_json(manifest_out, manifest_payload)
    return receipt_payload, manifest_out, manifest_payload


def prepare_launcher_convergence_bundle(
    *,
    workspace_root: Path,
    artifact_root: Path,
    receipt_path: Path,
    run_token: str,
    generated_at: str,
    mode: str,
    catalog_path: Path,
    entry_id: str,
    receipt_family: str,
    receipt_payload: dict[str, Any],
    evidence_record_inputs: list[dict[str, Any]],
    notes: list[str] | None = None,
    manifest_out: Path | None = None,
) -> tuple[dict[str, Any], Path, dict[str, Any]]:
    manifest_out = manifest_out.resolve() if manifest_out is not None else manifest_path(artifact_root, run_token)
    next_receipt = dict(receipt_payload)
    next_receipt["evidence_ref"] = str(receipt_path.resolve())
    next_receipt["manifest_ref"] = str(manifest_out)
    records: list[dict[str, Any]] = []
    for row in evidence_record_inputs:
        if not str(row.get("kind", "")).strip() or not str(row.get("path", "")).strip():
            continue
        payload_override = next_receipt if bool(row.get("use_prepared_receipt_payload")) else None
        if payload_override is None and isinstance(row.get("payload"), dict):
            payload_override = row.get("payload")
        records.append(
            build_manifest_record(
                kind=str(row.get("kind", "")).strip(),
                path=Path(str(row.get("path", "")).strip()).resolve(),
                workspace_root=workspace_root,
                command=row.get("command", ""),
                rc=int(row.get("rc", 0)),
                timestamp=str(row.get("timestamp", "")).strip(),
                tmp_path=str(row.get("tmp_path", "")).strip(),
                payload_override=payload_override,
            )
        )

    manifest_payload = build_launcher_convergence_manifest(
        workspace_root=workspace_root,
        artifact_root=artifact_root,
        receipt_path=receipt_path,
        run_token=run_token,
        generated_at=generated_at,
        mode=mode,
        catalog_path=catalog_path,
        entry_id=entry_id,
        receipt_family=receipt_family,
        evidence_records=records,
        notes=notes,
    )
    return next_receipt, manifest_out, manifest_payload
