#!/usr/bin/env python3
from __future__ import annotations

from release_readiness_governance_probe_projection_common import (
    RELEASE_READINESS_GOVERNANCE_PROBE_SURFACE_CONSTRAINTS,
)
from release_readiness_repo_global_closure_projection_common import (
    RELEASE_READINESS_REPO_GLOBAL_CLOSURE_PROJECTION_MARKER,
)
from release_readiness_required_gate_bundle_projection_common import (
    RELEASE_READINESS_REQUIRED_GATE_BUNDLE_PROJECTION_SURFACE_CONSTRAINTS,
)
from runtime_summary_surface_governance_common import (
    RUNTIME_SUMMARY_SURFACE_GOVERNANCE_PROBE,
)


RELEASE_CLOSURE_CONTINUATION_IN_PROGRESS_MARKER = "summary_lifecycle_status=IN_PROGRESS"
RELEASE_CLOSURE_CONTINUATION_CHECKPOINT_KIND_MARKER = (
    "summary_checkpoint_kind=checkpoint"
)
RELEASE_CLOSURE_CONTINUATION_STABLE_PREWRITE_SNAPSHOT_MARKER = (
    "stable prewrite snapshot"
)
RELEASE_CLOSURE_CONTINUATION_RUNNER_MARKER = (
    "scripts/run_release_readiness_continuation.py"
)
RELEASE_CLOSURE_CONTINUATION_CALLER_CWD_MARKER = "caller cwd"
RELEASE_CLOSURE_SUMMARY_CONTINUATION_FINALIZED_MARKER = (
    "summary_lifecycle_status=FINALIZED"
)
RELEASE_CLOSURE_SUMMARY_CONTINUATION_FINAL_CHECKPOINT_MARKER = (
    "summary_checkpoint_kind=final"
)
RELEASE_CLOSURE_SUMMARY_CONTINUATION_RESUME_CAPTURE_MODE_MARKER = (
    "resume_capture_mode=stable_prewrite_snapshot"
)
RELEASE_CLOSURE_SUMMARY_CONTINUATION_SAME_PATH_AS_SUMMARY_OUT_MARKER = (
    "same_path_as_summary_out"
)

RELEASE_CLOSURE_CONTINUATION_BASE_MARKERS: tuple[str, ...] = (
    RELEASE_CLOSURE_CONTINUATION_IN_PROGRESS_MARKER,
    RELEASE_CLOSURE_CONTINUATION_CHECKPOINT_KIND_MARKER,
    RELEASE_CLOSURE_CONTINUATION_STABLE_PREWRITE_SNAPSHOT_MARKER,
    RELEASE_CLOSURE_CONTINUATION_RUNNER_MARKER,
    RUNTIME_SUMMARY_SURFACE_GOVERNANCE_PROBE,
    "scripts/ci/run_release_readiness_summary_binding_probes_ci.sh",
    "scripts/ci/run_release_readiness_continuation_probes_ci.sh",
    "scripts/ci/run_release_plane_context_resolution_probes_ci.sh",
    *RELEASE_READINESS_GOVERNANCE_PROBE_SURFACE_CONSTRAINTS,
    RELEASE_CLOSURE_CONTINUATION_CALLER_CWD_MARKER,
)

RELEASE_CLOSURE_SUMMARY_CONTINUATION_MARKERS: tuple[str, ...] = (
    RELEASE_CLOSURE_CONTINUATION_IN_PROGRESS_MARKER,
    RELEASE_CLOSURE_CONTINUATION_CHECKPOINT_KIND_MARKER,
    RELEASE_CLOSURE_SUMMARY_CONTINUATION_FINALIZED_MARKER,
    RELEASE_CLOSURE_SUMMARY_CONTINUATION_FINAL_CHECKPOINT_MARKER,
    RELEASE_CLOSURE_CONTINUATION_STABLE_PREWRITE_SNAPSHOT_MARKER,
    RELEASE_CLOSURE_SUMMARY_CONTINUATION_RESUME_CAPTURE_MODE_MARKER,
    RELEASE_CLOSURE_SUMMARY_CONTINUATION_SAME_PATH_AS_SUMMARY_OUT_MARKER,
    *RELEASE_CLOSURE_CONTINUATION_BASE_MARKERS[3:-1],
    *RELEASE_READINESS_REQUIRED_GATE_BUNDLE_PROJECTION_SURFACE_CONSTRAINTS,
    RELEASE_CLOSURE_CONTINUATION_CALLER_CWD_MARKER,
)

RELEASE_CLOSURE_BOUNDARY_CONTINUATION_MARKERS: tuple[str, ...] = (
    *RELEASE_CLOSURE_CONTINUATION_BASE_MARKERS[:-1],
    RELEASE_READINESS_REPO_GLOBAL_CLOSURE_PROJECTION_MARKER,
    RELEASE_CLOSURE_CONTINUATION_CALLER_CWD_MARKER,
)
